### ISSUE TITLE
Cannot install requirements

### ISSUE THREAD

**Issue by omikron88** [Madhuvod/VoxLingua#1]
Hello, 
how to install requirements?

I used 
conda create -n vox python=3.10.15
pip install -r requirements.txt

at amd64 Ubuntu Linux

It gives me 
ERROR: Cannot install -r requirements.txt (line 58) and -r requirements.txt (line 97) because these package versions have conflicting dependencies.

The conflict is caused by:
    openai-whisper 20231117 depends on triton<3 and >=2.0.0
    torch 2.4.1 depends on triton==3.0.0; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.13"

How to install it?

**Comment by Madhuvod** [comment]
hey @omikron88, thanks for raising this issue, the model is still in the development phase, a few errors and issues that I have to deal with. It'll be done in a week - will talk to you then :)
